services:
  server:
    build:
      context: ..
      dockerfile: docker-compose/dockerfile.env
    ports:
      - "5500:8080"
    volumes:
      - ./config:/app/config
    networks:
      my_network:
        ipv4_address: 172.20.0.10

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
